package cn.edu.zime.domain;

import java.io.Serializable;
import java.util.Date;


public class Academy  implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACADEMY.ID
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACADEMY.ACAD_YEAR
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private String acadYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACADEMY.ACADEMY_CODE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private String academyCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACADEMY.START_DATE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ACADEMY.STOP_DATE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private Date stopDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACADEMY.ID
	 * @return  the value of ACADEMY.ID
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACADEMY.ID
	 * @param id  the value for ACADEMY.ID
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACADEMY.ACAD_YEAR
	 * @return  the value of ACADEMY.ACAD_YEAR
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public String getAcadYear() {
		return acadYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACADEMY.ACAD_YEAR
	 * @param acadYear  the value for ACADEMY.ACAD_YEAR
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setAcadYear(String acadYear) {
		this.acadYear = acadYear == null ? null : acadYear.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACADEMY.ACADEMY_CODE
	 * @return  the value of ACADEMY.ACADEMY_CODE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public String getAcademyCode() {
		return academyCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACADEMY.ACADEMY_CODE
	 * @param academyCode  the value for ACADEMY.ACADEMY_CODE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setAcademyCode(String academyCode) {
		this.academyCode = academyCode == null ? null : academyCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACADEMY.START_DATE
	 * @return  the value of ACADEMY.START_DATE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACADEMY.START_DATE
	 * @param startDate  the value for ACADEMY.START_DATE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ACADEMY.STOP_DATE
	 * @return  the value of ACADEMY.STOP_DATE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public Date getStopDate() {
		return stopDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ACADEMY.STOP_DATE
	 * @param stopDate  the value for ACADEMY.STOP_DATE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setStopDate(Date stopDate) {
		this.stopDate = stopDate;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 339752213707135364L;
}