package cn.edu.zime.domain;

import java.io.Serializable;
import java.util.Date;


public class Board implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3641580216382857815L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD.TITLE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD.CONTENTS
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String contents;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD.FEEDBACK_TIME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Date feedbackTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD.FEEDBACK_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String feedbackId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOARD.FEEDBACK_STATE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String feedbackState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD.ID
     *
     * @return the value of BOARD.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD.ID
     *
     * @param id the value for BOARD.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD.TITLE
     *
     * @return the value of BOARD.TITLE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD.TITLE
     *
     * @param title the value for BOARD.TITLE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD.CONTENTS
     *
     * @return the value of BOARD.CONTENTS
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD.CONTENTS
     *
     * @param contents the value for BOARD.CONTENTS
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setContents(String contents) {
        this.contents = contents == null ? null : contents.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD.FEEDBACK_TIME
     *
     * @return the value of BOARD.FEEDBACK_TIME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Date getFeedbackTime() {
        return feedbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD.FEEDBACK_TIME
     *
     * @param feedbackTime the value for BOARD.FEEDBACK_TIME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setFeedbackTime(Date feedbackTime) {
        this.feedbackTime = feedbackTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD.FEEDBACK_ID
     *
     * @return the value of BOARD.FEEDBACK_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getFeedbackId() {
        return feedbackId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD.FEEDBACK_ID
     *
     * @param feedbackId the value for BOARD.FEEDBACK_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setFeedbackId(String feedbackId) {
        this.feedbackId = feedbackId == null ? null : feedbackId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOARD.FEEDBACK_STATE
     *
     * @return the value of BOARD.FEEDBACK_STATE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getFeedbackState() {
        return feedbackState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOARD.FEEDBACK_STATE
     *
     * @param feedbackState the value for BOARD.FEEDBACK_STATE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setFeedbackState(String feedbackState) {
        this.feedbackState = feedbackState == null ? null : feedbackState.trim();
    }
}