package cn.edu.zime.domain;

import java.io.Serializable;


public class Classes implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = -6501197331598727211L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASSES.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASSES.CLASS_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String classCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASSES.CLASS_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASSES.PRO_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CLASSES.CLASS_DESCRIPTION
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String classDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASSES.ID
     *
     * @return the value of CLASSES.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASSES.ID
     *
     * @param id the value for CLASSES.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASSES.CLASS_CODE
     *
     * @return the value of CLASSES.CLASS_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASSES.CLASS_CODE
     *
     * @param classCode the value for CLASSES.CLASS_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setClassCode(String classCode) {
        this.classCode = classCode == null ? null : classCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASSES.CLASS_NAME
     *
     * @return the value of CLASSES.CLASS_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASSES.CLASS_NAME
     *
     * @param className the value for CLASSES.CLASS_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASSES.PRO_ID
     *
     * @return the value of CLASSES.PRO_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASSES.PRO_ID
     *
     * @param proId the value for CLASSES.PRO_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CLASSES.CLASS_DESCRIPTION
     *
     * @return the value of CLASSES.CLASS_DESCRIPTION
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getClassDescription() {
        return classDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CLASSES.CLASS_DESCRIPTION
     *
     * @param classDescription the value for CLASSES.CLASS_DESCRIPTION
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setClassDescription(String classDescription) {
        this.classDescription = classDescription == null ? null : classDescription.trim();
    }
}