package cn.edu.zime.domain;

import java.io.Serializable;
import java.util.Date;


public class ConstantPeriod  implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 203609456718535343L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTANT_PERIOD.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTANT_PERIOD.PERIOD_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer periodCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTANT_PERIOD.BEGIN_TIME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CONSTANT_PERIOD.END_TIME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTANT_PERIOD.ID
     *
     * @return the value of CONSTANT_PERIOD.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTANT_PERIOD.ID
     *
     * @param id the value for CONSTANT_PERIOD.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTANT_PERIOD.PERIOD_CODE
     *
     * @return the value of CONSTANT_PERIOD.PERIOD_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getPeriodCode() {
        return periodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTANT_PERIOD.PERIOD_CODE
     *
     * @param periodCode the value for CONSTANT_PERIOD.PERIOD_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setPeriodCode(Integer periodCode) {
        this.periodCode = periodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTANT_PERIOD.BEGIN_TIME
     *
     * @return the value of CONSTANT_PERIOD.BEGIN_TIME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTANT_PERIOD.BEGIN_TIME
     *
     * @param beginTime the value for CONSTANT_PERIOD.BEGIN_TIME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CONSTANT_PERIOD.END_TIME
     *
     * @return the value of CONSTANT_PERIOD.END_TIME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CONSTANT_PERIOD.END_TIME
     *
     * @param endTime the value for CONSTANT_PERIOD.END_TIME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}