package cn.edu.zime.domain;

import java.io.Serializable;


public class CouDivide  implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 6561851617153010093L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUDIVIDE.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUDIVIDE.COU_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer couId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUDIVIDE.CLASS_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUDIVIDE.TERCHER_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String tercherCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUDIVIDE.ID
     *
     * @return the value of COUDIVIDE.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUDIVIDE.ID
     *
     * @param id the value for COUDIVIDE.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUDIVIDE.COU_ID
     *
     * @return the value of COUDIVIDE.COU_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getCouId() {
        return couId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUDIVIDE.COU_ID
     *
     * @param couId the value for COUDIVIDE.COU_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setCouId(Integer couId) {
        this.couId = couId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUDIVIDE.CLASS_ID
     *
     * @return the value of COUDIVIDE.CLASS_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUDIVIDE.CLASS_ID
     *
     * @param classId the value for COUDIVIDE.CLASS_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUDIVIDE.TERCHER_CODE
     *
     * @return the value of COUDIVIDE.TERCHER_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getTercherCode() {
        return tercherCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUDIVIDE.TERCHER_CODE
     *
     * @param tercherCode the value for COUDIVIDE.TERCHER_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setTercherCode(String tercherCode) {
        this.tercherCode = tercherCode == null ? null : tercherCode.trim();
    }
}