package cn.edu.zime.domain;

import java.io.Serializable;


public class Couse implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 3957626810253788961L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUSE.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUSE.COU_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String couCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUSE.COU_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String couName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUSE.COU_DESCRIPTION
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String couDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUSE.TOTAL_PERIOD
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer totalPeriod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUSE.ID
     *
     * @return the value of COUSE.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUSE.ID
     *
     * @param id the value for COUSE.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUSE.COU_CODE
     *
     * @return the value of COUSE.COU_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getCouCode() {
        return couCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUSE.COU_CODE
     *
     * @param couCode the value for COUSE.COU_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setCouCode(String couCode) {
        this.couCode = couCode == null ? null : couCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUSE.COU_NAME
     *
     * @return the value of COUSE.COU_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getCouName() {
        return couName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUSE.COU_NAME
     *
     * @param couName the value for COUSE.COU_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setCouName(String couName) {
        this.couName = couName == null ? null : couName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUSE.COU_DESCRIPTION
     *
     * @return the value of COUSE.COU_DESCRIPTION
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getCouDescription() {
        return couDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUSE.COU_DESCRIPTION
     *
     * @param couDescription the value for COUSE.COU_DESCRIPTION
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setCouDescription(String couDescription) {
        this.couDescription = couDescription == null ? null : couDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUSE.TOTAL_PERIOD
     *
     * @return the value of COUSE.TOTAL_PERIOD
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getTotalPeriod() {
        return totalPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUSE.TOTAL_PERIOD
     *
     * @param totalPeriod the value for COUSE.TOTAL_PERIOD
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setTotalPeriod(Integer totalPeriod) {
        this.totalPeriod = totalPeriod;
    }
}