package cn.edu.zime.domain;

import java.io.Serializable;


public class Department implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4676527546996602217L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEP_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String depCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.DEP_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String depName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.ID
     *
     * @return the value of DEPARTMENT.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.ID
     *
     * @param id the value for DEPARTMENT.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEP_CODE
     *
     * @return the value of DEPARTMENT.DEP_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getDepCode() {
        return depCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEP_CODE
     *
     * @param depCode the value for DEPARTMENT.DEP_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setDepCode(String depCode) {
        this.depCode = depCode == null ? null : depCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.DEP_NAME
     *
     * @return the value of DEPARTMENT.DEP_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.DEP_NAME
     *
     * @param depName the value for DEPARTMENT.DEP_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }
}