package cn.edu.zime.domain;

import java.io.Serializable;

import java.util.Date;

public class Dictionary implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.ID
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.DICT_CODE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private String dictCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.PARENT_CODE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private String parentCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.PARENT_ID
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.VALUE_ZH
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private String valueZh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.VALUE_EN
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private String valueEn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.DICT_LEVEL
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private String dictLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.REMARK
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.CREATE_TIME
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.UPDATE_TIME
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.CREATER
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private String creater;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.UPDATER
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private String updater;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column DICTIONARY.TARGET_TABLE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	private String targetTable;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.ID
	 * @return  the value of DICTIONARY.ID
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.ID
	 * @param id  the value for DICTIONARY.ID
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.DICT_CODE
	 * @return  the value of DICTIONARY.DICT_CODE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public String getDictCode() {
		return dictCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.DICT_CODE
	 * @param dictCode  the value for DICTIONARY.DICT_CODE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setDictCode(String dictCode) {
		this.dictCode = dictCode == null ? null : dictCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.PARENT_CODE
	 * @return  the value of DICTIONARY.PARENT_CODE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public String getParentCode() {
		return parentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.PARENT_CODE
	 * @param parentCode  the value for DICTIONARY.PARENT_CODE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setParentCode(String parentCode) {
		this.parentCode = parentCode == null ? null : parentCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.PARENT_ID
	 * @return  the value of DICTIONARY.PARENT_ID
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.PARENT_ID
	 * @param parentId  the value for DICTIONARY.PARENT_ID
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.VALUE_ZH
	 * @return  the value of DICTIONARY.VALUE_ZH
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public String getValueZh() {
		return valueZh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.VALUE_ZH
	 * @param valueZh  the value for DICTIONARY.VALUE_ZH
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setValueZh(String valueZh) {
		this.valueZh = valueZh == null ? null : valueZh.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.VALUE_EN
	 * @return  the value of DICTIONARY.VALUE_EN
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public String getValueEn() {
		return valueEn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.VALUE_EN
	 * @param valueEn  the value for DICTIONARY.VALUE_EN
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setValueEn(String valueEn) {
		this.valueEn = valueEn == null ? null : valueEn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.DICT_LEVEL
	 * @return  the value of DICTIONARY.DICT_LEVEL
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public String getDictLevel() {
		return dictLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.DICT_LEVEL
	 * @param dictLevel  the value for DICTIONARY.DICT_LEVEL
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setDictLevel(String dictLevel) {
		this.dictLevel = dictLevel == null ? null : dictLevel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.REMARK
	 * @return  the value of DICTIONARY.REMARK
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.REMARK
	 * @param remark  the value for DICTIONARY.REMARK
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.CREATE_TIME
	 * @return  the value of DICTIONARY.CREATE_TIME
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.CREATE_TIME
	 * @param createTime  the value for DICTIONARY.CREATE_TIME
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.UPDATE_TIME
	 * @return  the value of DICTIONARY.UPDATE_TIME
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.UPDATE_TIME
	 * @param updateTime  the value for DICTIONARY.UPDATE_TIME
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.CREATER
	 * @return  the value of DICTIONARY.CREATER
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public String getCreater() {
		return creater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.CREATER
	 * @param creater  the value for DICTIONARY.CREATER
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setCreater(String creater) {
		this.creater = creater == null ? null : creater.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.UPDATER
	 * @return  the value of DICTIONARY.UPDATER
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public String getUpdater() {
		return updater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.UPDATER
	 * @param updater  the value for DICTIONARY.UPDATER
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setUpdater(String updater) {
		this.updater = updater == null ? null : updater.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column DICTIONARY.TARGET_TABLE
	 * @return  the value of DICTIONARY.TARGET_TABLE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public String getTargetTable() {
		return targetTable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column DICTIONARY.TARGET_TABLE
	 * @param targetTable  the value for DICTIONARY.TARGET_TABLE
	 * @mbggenerated  Sun Sep 07 16:01:54 CST 2014
	 */
	public void setTargetTable(String targetTable) {
		this.targetTable = targetTable == null ? null : targetTable.trim();
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 4966921467221204747L;
}