package cn.edu.zime.domain;

import java.io.Serializable;

import java.util.List;


public class Groups implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4741290212804811604L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUPS.GID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUPS.GNAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String gname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUPS.DESCRIPTION
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GROUPS.PARENT_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer parentId;
    
    private List<Permission> permission;

    public List<Permission> getPermission() {
		return permission;
	}

	public void setPermission(List<Permission> permission) {
		this.permission = permission;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUPS.GID
     *
     * @return the value of GROUPS.GID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUPS.GID
     *
     * @param gid the value for GROUPS.GID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUPS.GNAME
     *
     * @return the value of GROUPS.GNAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUPS.GNAME
     *
     * @param gname the value for GROUPS.GNAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setGname(String gname) {
        this.gname = gname == null ? null : gname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUPS.DESCRIPTION
     *
     * @return the value of GROUPS.DESCRIPTION
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUPS.DESCRIPTION
     *
     * @param description the value for GROUPS.DESCRIPTION
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GROUPS.PARENT_ID
     *
     * @return the value of GROUPS.PARENT_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GROUPS.PARENT_ID
     *
     * @param parentId the value for GROUPS.PARENT_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}