package cn.edu.zime.domain;

import java.io.Serializable;



public class IpMapping implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 8839675171768556720L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IPMAPPING.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IPMAPPING.USER_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IPMAPPING.USER_IP
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String userIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column IPMAPPING.USER_IP_V6
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String userIpV6;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPMAPPING.ID
     *
     * @return the value of IPMAPPING.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPMAPPING.ID
     *
     * @param id the value for IPMAPPING.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPMAPPING.USER_CODE
     *
     * @return the value of IPMAPPING.USER_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPMAPPING.USER_CODE
     *
     * @param userCode the value for IPMAPPING.USER_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPMAPPING.USER_IP
     *
     * @return the value of IPMAPPING.USER_IP
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPMAPPING.USER_IP
     *
     * @param userIp the value for IPMAPPING.USER_IP
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setUserIp(String userIp) {
        this.userIp = userIp == null ? null : userIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column IPMAPPING.USER_IP_V6
     *
     * @return the value of IPMAPPING.USER_IP_V6
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getUserIpV6() {
        return userIpV6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column IPMAPPING.USER_IP_V6
     *
     * @param userIpV6 the value for IPMAPPING.USER_IP_V6
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setUserIpV6(String userIpV6) {
        this.userIpV6 = userIpV6 == null ? null : userIpV6.trim();
    }
}