package cn.edu.zime.domain;

import java.io.Serializable;



public class Permission implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 2558087018311373100L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.PER_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String perName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.DESCRIPTION
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.REQ_URL
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String reqUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.PARENT_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PERMISSION.GID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer gid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.ID
     *
     * @return the value of PERMISSION.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.ID
     *
     * @param id the value for PERMISSION.ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.PER_NAME
     *
     * @return the value of PERMISSION.PER_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.PER_NAME
     *
     * @param perName the value for PERMISSION.PER_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setPerName(String perName) {
        this.perName = perName == null ? null : perName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.DESCRIPTION
     *
     * @return the value of PERMISSION.DESCRIPTION
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.DESCRIPTION
     *
     * @param description the value for PERMISSION.DESCRIPTION
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.REQ_URL
     *
     * @return the value of PERMISSION.REQ_URL
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getReqUrl() {
        return reqUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.REQ_URL
     *
     * @param reqUrl the value for PERMISSION.REQ_URL
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setReqUrl(String reqUrl) {
        this.reqUrl = reqUrl == null ? null : reqUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.PARENT_ID
     *
     * @return the value of PERMISSION.PARENT_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.PARENT_ID
     *
     * @param parentId the value for PERMISSION.PARENT_ID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PERMISSION.GID
     *
     * @return the value of PERMISSION.GID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PERMISSION.GID
     *
     * @param gid the value for PERMISSION.GID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }
}