package cn.edu.zime.domain;

import java.io.Serializable;

import cn.edu.zime.base.domain.TeaPermission;
import cn.edu.zime.base.domain.UserBase;


public class Teacher extends UserBase implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = -2238921746473481560L;
	
	public Teacher () { 
		setUserPermission(new TeaPermission());
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.TEA_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String teaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.TEA_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String teaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.PHONE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.SEX
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.PASS_WORD
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private String passWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEACHER.GID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    private Integer gid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEACHER.TEA_CODE
     *
     * @return the value of TEACHER.TEA_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getTeaCode() {
        return teaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEACHER.TEA_CODE
     *
     * @param teaCode the value for TEACHER.TEA_CODE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setTeaCode(String teaCode) {
        this.teaCode = teaCode == null ? null : teaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEACHER.TEA_NAME
     *
     * @return the value of TEACHER.TEA_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getTeaName() {
        return teaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEACHER.TEA_NAME
     *
     * @param teaName the value for TEACHER.TEA_NAME
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setTeaName(String teaName) {
        this.teaName = teaName == null ? null : teaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEACHER.PHONE
     *
     * @return the value of TEACHER.PHONE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEACHER.PHONE
     *
     * @param phone the value for TEACHER.PHONE
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEACHER.SEX
     *
     * @return the value of TEACHER.SEX
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEACHER.SEX
     *
     * @param sex the value for TEACHER.SEX
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEACHER.PASS_WORD
     *
     * @return the value of TEACHER.PASS_WORD
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEACHER.PASS_WORD
     *
     * @param passWord the value for TEACHER.PASS_WORD
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEACHER.GID
     *
     * @return the value of TEACHER.GID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public Integer getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEACHER.GID
     *
     * @param gid the value for TEACHER.GID
     *
     * @mbggenerated Sun Sep 07 10:33:37 CST 2014
     */
    public void setGid(Integer gid) {
        this.gid = gid;
    }
}